name: Publish Python Package to PyPI

# This is the trigger: the workflow runs ONLY when a new release is created on GitHub.
on:
  release:
    types: [published]

jobs:
  # The 'build-and-publish' job defines all the steps needed.
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest # The job runs on a fresh virtual machine hosted by GitHub.

    steps:
      # Step 1: Check out your repository's code so the job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # You can change this to your preferred version.

      # Step 3: Install the necessary build tools.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the package (this creates the .whl and .tar.gz files).
      - name: Build package
        run: python -m build

      # Step 5: This is the key publishing step.
      - name: Publish package to PyPI
        # This uses a pre-made, trusted action from the Python Packaging Authority (PyPA).
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # The password is automatically and securely pulled from your GitHub Secrets.
          password: ${{ secrets.PYPI_API_TOKEN }}